### PR TITLE
Kan 8 cart wishlist code

### PR DESCRIPTION
**Pull request by vivektalpada07**

### CODE REVIEW

**Review by chathu-123 — COMMENTED** [review]
It is good. I think need to add only user auth in context folder and the rest should be under services folder.

**Comment by vivektalpada07** [comment]
> It is good. I think need to add only user auth in context folder and the rest should be under services folder.
there is context folder and in it every services and user context is there so I think there is no need for it

**Comment by Hem9025** [comment]
> > It is good. I think need to add only user auth in context folder and the rest should be under services folder.
> > there is context folder and in it every services and user context is there so I think there is no need for it

**Comment by Hem9025** [comment]
I think vivek is correct we will keep all services and auth in one file. And all other file like other js file in component.

**Review by abhistyalish2802 — APPROVED** [review]
I have reviewed the code it is working well. You can make css for this page  more effective so page looks good.

**Pull request merged**
